### ISSUE TITLE
[2] Spike: Indiana University Allinson Flex Overrides?

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#103]
# Summary

IU/ESSI was the project that Allinson Flex (flex) was originally created for. They currently have a forked repo of the flex gem... but do they also have any flex related overrides within their [project](https://github.com/IU-Libraries-Joint-Development/essi)? 

# Acceptance Criteria

- [ ] This spike is to explore their repo and take note of any overrides. Do not bring them over just yet; let's talk about what you find first. 
  - [ ] This search should also include looking into branches that aren't main

- [ ] Please also look into and evaluate any code diffs that happened other branches than main, 

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

Linked items:

Relates to:

- [3]Contribute Essie admin only back
- [3]Copy over Indiana University's Allinson Flex related work

**Comment by ShanaLMoore** [comment]
- [ ] add dynamic metadata to iiif manifest  - https://github.com/IU-Libraries-Joint-Development/essi/commit/96a2fa220345ef6b2d560bfb7741afa5b2f37216

Our implementation of this: https://gitlab.com/notch8/utk-hyku/-/blob/main/app/presenters/hyrax/iiif_manifest_presenter_decorator.rb#L15-43

**Comment by ShanaLMoore** [comment]
general search for flex: https://github.com/IU-Libraries-Joint-Development/essi/search?p=1&q=allinson_flex

"modified from allinson_flex": https://github.com/IU-Libraries-Joint-Development/essi/search?q=modified+from+allinson_flex

**Comment by ShanaLMoore** [comment]
- [x] IU has a way of selecting which profile version to use, when importing with bulkrax. It defaults to the latest. Also the user is able to specify it "object by object": 


![Image](https://user-images.githubusercontent.com/10081604/198126792-ee154c79-66b2-44f6-92e1-9b314781e8f3.png)


https://youtu.be/2Z1b_s1wrU0?t=1136

Per a chat with Crystal, we will not be implementing this for UTK unless it becomes an issue/request.

**Comment by laritakr** [comment]
IU has their own version of the [item view partial](https://github.com/IU-Libraries-Joint-Development/essi/blob/main/app/views/records/edit_fields/_default.html.erb), which uses [helpers for dynamic labels and dynamic hints](https://github.com/IU-Libraries-Joint-Development/essi/blob/80410a95173e148ba447af37cd0c59213363b01a/app/helpers/application_helper.rb#L33-L43). 

This apparently allows for internationalization by using locale to look up the terms and hints. I haven't traced how they override the import process yet, so it's not clear if they use the terms in the metadata profile file or not. Allinson Flex importer does not save the description to use as the hint.

**Comment by ShanaLMoore** [comment]
- [ ]  [ESSI-1382] Refactor dynamic label, hint lookup into helpers 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/aaf601a58980715074ac1963f72d57b5a31f4f9e

- [x]  [ESSI-1465][ESSI-1466] log profile construction errors 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/ac3585b326f8266d4ab3c18b1aa7a19d2275dfc6

- [ ]  [ESSI-1382] Refactor #display_label, add usage_guidelines in schema 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/9d85c5e5e27396909644a14f65b43ca76eb4f0e4

- [x]  [ESSI-1382] Refactor property texts into separate method 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/93eaa1ab3787118fc63636c1a1650206b81e7ac2

- [x]  [ESSI-1321][ESSI-1445] add admin_only indexing display modifier 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/4401fa19040539cf75b2c24cddae3b9b71879370

- [x]  [ESSI-1465][ESSI-1466] raise more specific ProfileText error messages 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/3f19bdeb5394e378f07fe0f1500bc8b9501e52ce

- [x]  [ESSI-1539] Tweak dynamic indexing results: make ActiveTriples Arrays 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/dbcbb22d82744e62bc3a580f7b27ca640236896f

- [x]  [ESSI-1370] Soften condition for AllinsonFlex::Profile before_destroy… 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/0929763f445879277a66278cf16958226a1a14e8

- [x]  [ESSI-1519] Skip allinson_flex load in Collections authority 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/581fcd1a983dd3dc310b2721d4e9334f9fd76f95

- [ ]  [ESSI-1670] refactor presenter pattern for custom rendered attributes 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/4fd10a9700621d1393499592f68cad3ab65e322a

- [ ]  [ESSI-1646] improve flexible metadata reliability in bulkrax import 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/b1da8d392f886cea5a3da35f61093ba9aa29278e

**Comment by ShanaLMoore** [comment]
PR search for allinson: https://github.com/IU-Libraries-Joint-Development/essi/pulls?q=is%3Apr+is%3Aclosed+allinson

**Comment by ShanaLMoore** [comment]
- [x]  [ESSI-1692] dynamic manifest metadata #480 https://github.com/IU-Libraries-Joint-Development/essi/pull/480
- [x]  [ESSI-1614] catch errors rendering #new with a new AllinsonFlex profile #455 https://github.com/IU-Libraries-Joint-Development/essi/pull/455
- [ ]  [ESSI-1616] "description" display configurable via allinson_flex #449 https://github.com/IU-Libraries-Joint-Development/essi/pull/449
- [x]  [ESSI-1539] tweak dynamic indexing #369 https://github.com/IU-Libraries-Joint-Development/essi/pull/369
- [x]  [ESSI-1370] Bulkrax export bugs #336 https://github.com/IU-Libraries-Joint-Development/essi/pull/336/files
- [ ]  [ESSI-1382] Pull edit from hint text from usage_guidlines in allinson_flex #331 https://github.com/IU-Libraries-Joint-Development/essi/pull/331/files
- [x]  [ESSI-1135] [ESSI-1214] Fix dynamic facets #258 https://github.com/IU-Libraries-Joint-Development/essi/pull/258/files

**Comment by ShanaLMoore** [comment]
The results of this ticket will be the creation of #240
