### ISSUE TITLE
[2]Spike: IIIF AV gem compatibility with Hyrax

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#129]
# Summary
Investigate the AV gem and understanding how big of a lift it would be to bring it up to Hyrax 3. 

# Acceptance Criteria

- [ ] Tickets to execute plan have been created

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by crisr15** [comment]
Jeremy: 
In this document we’re looking at [[2]Spike: IIIF AV gem compatibility with Hyrax (#220) · Issues · notch8 / UTK-Hyku · GitLab](https://gitlab.com/notch8/utk-hyku/-/issues/220).

For consideration we want to look at some high level things:

-   The dependency graph
-   The change history of shared dependencies
-   The implementation (e.g. the code in the state we want to reference)
-   Coordination of dependency upgrades; the administrative


<a id="org4b0a295"></a>

# Recomendation

The `hyrax-iiif_av` gem has minor dependency conflicts with Hyrax in regards to `iiif_manifest`.  We want to leverage new `iiif_manifest` functionality that @kirkkwang has been pushing forward.  So the `hyrax-iiif_av` gem should require `~> 1.x`; this aligns with `iiif_manifest` changes.  It also aligns with what Hyrax allows for the `iiif_manifest`.

Resolving the dependency conflicts is a small (e.g. contained) lift; in part because the code-base is small and the changes to upgrade versions is also minimal.


<a id="orgd8c411e"></a>

## Task List

**Note:** Our plan, thusfar, is that we do not need to make changes to Hyrax.

Make the gems work for a Hyrax 3.x version.  The below listed changes will get us the `iiif_manifest` version we want and allow us to use `hyrax-iiif_av` at the `HEAD` of `main` (e.g. the latest unreleased version).  In addition with these changes, the `hyrax-iiif_av` gem can continue to work with Hyrax `v2.9.4`; because that version has a `iiif_manifest` range of `> 0.3 and < 0.6`.

-   Bump the `hyrax-iiif_av.gemspec` (on a branch) to `> 0.5` for the `iiif_manifest` changes; this allows us to use the `iiif_manifest` at the 1.x version that @kirkkwang has been working on.
-   Bump the `hyrax-iiif_av.gemspec` (on a branch) to `~> 2.9` and `< 5.0` for the `hyrax` changes.
-   In the Hyku Gemfile we add a gem reference to `hyrax-iiif_av` at the new branch.
-   In the Hyku Gemfile we add a gem reference to `iiif_manifest` at the 1.x version.

With the pre-work done of upgrading gem version, we need to test the above by running the generator for the `hyrax-iiif_av`.  This is the point where ambiguity enters.  It looks contained but we’ll be running a generator and needing to do some configuration.

We need to:

-   Per the documentation, include the appropriate modules on the Video and Audio; this could include CompoundObject.
-   Default assumption is an `:avalon` player, so we need to adjust configuration to [Universal Viewer](http://universalviewer.io).

**Bonus Work to Consider**

-   Add a partial for [Universal Viewer](http://universalviewer.io) in the `hyrax-iiif_av` gem.  Or is this the pathway forward?

Based on [Ticket Estimation | Wiki.js](https://playbook-staging.notch8.com/en/dev/ticket-estimation) this “epic” is a 5; in part because there are three related gems to consider but also because to “test” the upgrade, we basically need to do all of the work of implementing.

The task as written “Investigate the AV gem and understanding how big of a lift it would be to bring it up to Hyrax 3.” is narrower in scope than the above task list.  With the above task list, we would be delivering the IIIF AV gem into the UTK application.


<a id="orge648af8"></a>

# Investigation and General Notes

What follows are some scratch notes in perhaps incoherent order, but this was the “homework” portion of the analysis.

    s.add_dependency "rails", "~>5.1"
    s.add_dependency "blacklight"
    s.add_dependency "hyrax", "~> 2.9", ">= 2.9.4"
    s.add_dependency "iiif_manifest", "~> 0.5"

We look at the [hyrax-iiif\_av.gemspec](https://github.com/samvera-labs/hyrax-iiif_av/blob/888ad531ec08e6c1040d609321972e2147f0c702/hyrax-iiif_av.gemspec#L22-L25) for dependencies.  And we want to see what Hyrax is at/assumes and then what we need to change.  We are aiming for Hyrax 3.4.x.  But we want to also be mindful of Hyrax 4.0.x which is looming.

In the Hyrax v3.4.2 tag, we have the following:

    spec.add_dependency 'iiif_manifest', '>= 0.3', '< 2.0'

Looking at  [hyrax.gemspec](https://github.com/samvera/hyrax/blob/64c0bbf0dc0d3e1b49f040b50ea70d177cc9d8f6/hyrax.gemspec#L58) the Hyrax version has broader allowed range, both earlier versions and later versions.  This is a potential challenge, because if we incorporate the av gem as is, some folks may experience a version downgrade of the iiif\_manifest gem.

In the Hyrax v2.9.4 tag, we have the following:

    spec.add_dependency 'iiif_manifest', '>= 0.3', '< 0.60'

Next we have the mental framing.

We should look to see if Hyrax can go to at least `iiif_manifest ~> 0.5`; this is a worthwhile patch.  To do this we **should revisit** the change history of iiif\_manifest between 0.3 and 0.5.  This would ensure others wouldn’t experience a downshift.

Per Chris Colvard’s recommendation, we’re exploring adding this plugin into Hyrax; however, that would necessitate a v3.5 release, because we’re adding new functionality.  And depending on things, this could be a major release change; unlikely but possible.

So based on the scope, let’s make the gem 3.4.x compliant so the community could more easily take a 3.5 release path.  Also, there is a lot that goes into a samvera project release than a samvera labs project release.


<a id="orge740f03"></a>

## Let’s look at the gem

When looking at the gem, I like to approach from the outside in; that is from what the user sees down into the data structures and logic for handling a request.  In other words: views -> controllers -> models.

Let’s look at the files in `app` and `lib`

    cd ~/git/hyrax-iiif_av; tree app

    app
    ├── controllers
    │   ├── concerns
    │   │   └── hyrax
    │   │       └── iiif_av
    │   │           ├── auth_controller_behavior.rb
    │   │           └── controller_behavior.rb
    │   └── hyrax
    │       └── iiif_av
    │           └── iiif_av_controller.rb
    ├── models
    │   └── hyrax
    │       └── iiif_av
    │           └── manifest_range.rb
    └── presenters
        ├── concerns
        │   └── hyrax
        │       └── iiif_av
        │           ├── displays_content.rb
        │           └── displays_iiif_av.rb
        └── hyrax
            └── iiif_av
                └── iiif_file_set_presenter.rb
    
    15 directories, 7 files

    cd ~/git/hyrax-iiif_av; tree lib

    lib
    ├── generators
    │   └── hyrax
    │       └── iiif_av
    │           ├── add_to_work_type_generator.rb
    │           ├── install_avalon_player_generator.rb
    │           ├── install_generator.rb
    │           └── templates
    │               ├── AvalonIiifPlayer.js
    │               └── _avalon.html.erb
    ├── hyrax
    │   ├── iiif_av
    │   │   ├── configuration.rb
    │   │   ├── engine.rb
    │   │   ├── spec
    │   │   │   ├── shared_specs
    │   │   │   │   ├── controller_behavior.rb
    │   │   │   │   ├── displays_content.rb
    │   │   │   │   └── displays_iiif_av.rb
    │   │   │   └── shared_specs.rb
    │   │   └── version.rb
    │   └── iiif_av.rb
    └── tasks
        └── hyrax
            └── iiif_av_tasks.rake
    
    10 directories, 14 files

We want to look at both code complexity as well as what of Hyrax is touched by this gem.

The following will look for all references modules or classes in the Hyrax namespace that do no begin with the case insenstive `ii`; let’s skip `Hyrax::IiifAv`.

    cd ~/git/hyrax-iiif_av/ ; rg "Hyrax::[^I][^i]" --ignore-case .

    ./lib/hyrax/iiif_av/configuration.rb:          # Reverse engineering Hyrax::DerivativePath
    ./lib/hyrax/iiif_av/configuration.rb:          Hyrax::Engine.routes.url_helpers.download_path(file_set_id, file: filename)
    ./spec/controllers/generic_works_controller_spec.rb:describe Hyrax::GenericWorksController, type: :controller do
    ./spec/controllers/generic_works_controller_spec.rb:      class IiifAvWorkPresenter < Hyrax::GenericWorkPresenter
    ./spec/controllers/generic_works_controller_spec.rb:      let(:presenter) { Hyrax::GenericWorkPresenter.new(work_solr_document, ability, request) }
    ./spec/controllers/iiif_av_controller_spec.rb:        expect(response).to redirect_to Hyrax::Engine.routes.url_helpers.download_path(file_set_id, file: 'mp4', locale: nil)
    ./lib/generators/hyrax/iiif_av/install_generator.rb:        insert_into_file 'app/controllers/application_controller.rb', after: 'include Hyrax::Controller' do
    ./lib/generators/hyrax/iiif_av/add_to_work_type_generator.rb:        insert_into_file controller_file, after: 'include Hyrax::BreadcrumbsForWorks' do
    ./lib/generators/hyrax/iiif_av/add_to_work_type_generator.rb:        insert_into_file presenter_file, after: '< Hyrax::WorkShowPresenter' do
    ./lib/generators/hyrax/iiif_av/add_to_work_type_generator.rb:          "    Hyrax::MemberPresenterFactory.file_presenter_class = Hyrax::IiifAv::IiifFileSetPresenter\n" \
    ./lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb:  let(:parent_presenter) { double("Hyrax::GenericWorkPresenter", iiif_version: 2) }
    ./lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb:            { id: '1', label: 'high', file_location_uri: Hyrax::DerivativePath.derivative_path_for_reference(file_set_id, 'high.mp3') },
    ./lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb:            { id: '2', label: 'medium', file_location_uri: Hyrax::DerivativePath.derivative_path_for_reference(file_set_id, 'medium.mp3') }
    ./lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb:          let(:parent_presenter) { double("Hyrax::GenericWorkPresenter", iiif_version: 3) }
    ./lib/hyrax/iiif_av/spec/shared_specs/controller_behavior.rb:  let(:hyrax) { Hyrax::Engine.routes.url_helpers }
    ./lib/hyrax/iiif_av/spec/shared_specs/controller_behavior.rb:        # the following code assumes Hyrax::GenericWorksController::IIIF_DEFAULT_VERSION is 2;
    ./spec/presenters/displays_iiif_av_spec.rb:    class IiifAvWorkPresenter < Hyrax::GenericWorkPresenter
    ./spec/requests/auth_controller_behavior_spec.rb:      expect(response).to redirect_to Hyrax::Engine.routes.url_helpers.dashboard_path(locale: I18n.locale)
    ./spec/requests/auth_controller_behavior_spec.rb:        expect(response).to redirect_to Hyrax::Engine.routes.url_helpers.dashboard_path(locale: I18n.locale)
    ./spec/test_app_templates/lib/generators/test_app_generator.rb:    Hyrax::DatabaseMigrator.copy
    ./app/presenters/concerns/hyrax/iiif_av/displays_content.rb:          Hyrax::Engine.routes.url_helpers.download_url(solr_document, file: extension, host: request.base_url)
    ./app/controllers/concerns/hyrax/iiif_av/controller_behavior.rb:        # This forces the manifest action to call Hyrax::ManifestBuilderService.manifest_for
    ./app/controllers/concerns/hyrax/iiif_av/controller_behavior.rb:            (Flipflop.cache_work_iiif_manifest? ? Hyrax::CachingIiifManifestBuilder : Hyrax::ManifestBuilderService)

-   [X] ./spec/controllers/generic\_works\_controller\_spec.rb:describe Hyrax::GenericWorksController, type: :controller do
-   [X] ./spec/controllers/generic\_works\_controller\_spec.rb:      class IiifAvWorkPresenter < Hyrax::GenericWorkPresenter
-   [X] ./spec/controllers/generic\_works\_controller\_spec.rb:      let(:presenter) { Hyrax::GenericWorkPresenter.new(work\_solr\_document, ability, request) }
-   [X] ./spec/presenters/displays\_iiif\_av\_spec.rb:    class IiifAvWorkPresenter < Hyrax::GenericWorkPresenter
-   [X] ./spec/test\_app\_templates/lib/generators/test\_app\_generator.rb:    Hyrax::DatabaseMigrator.copy
-   [X] ./lib/generators/hyrax/iiif\_av/add\_to\_work\_type\_generator.rb:        insert\_into\_file controller\_file, after: 'include Hyrax::BreadcrumbsForWorks' do
-   [X] ./lib/generators/hyrax/iiif\_av/add\_to\_work\_type\_generator.rb:        insert\_into\_file presenter\_file, after: '< Hyrax::WorkShowPresenter' do
-   [X] ./lib/generators/hyrax/iiif\_av/add\_to\_work\_type\_generator.rb:          "    Hyrax::MemberPresenterFactory.file\_presenter\_class = Hyrax::IiifAv::IiifFileSetPresenter\n" \\
-   [X] ./spec/controllers/iiif\_av\_controller\_spec.rb:        expect(response).to redirect\_to Hyrax::Engine.routes.url\_helpers.download\_path(file\_set\_id, file: 'mp4', locale: nil)
-   [X] ./lib/generators/hyrax/iiif\_av/install\_generator.rb:        insert\_into\_file 'app/controllers/application\_controller.rb', after: 'include Hyrax::Controller' do
-   [X] ./spec/requests/auth\_controller\_behavior\_spec.rb:      expect(response).to redirect\_to Hyrax::Engine.routes.url\_helpers.dashboard\_path(locale: I18n.locale)
-   [X] ./spec/requests/auth\_controller\_behavior\_spec.rb:        expect(response).to redirect\_to Hyrax::Engine.routes.url\_helpers.dashboard\_path(locale: I18n.locale)
-   [X] ./lib/hyrax/iiif\_av/configuration.rb:          # Reverse engineering Hyrax::DerivativePath
-   [X] ./lib/hyrax/iiif\_av/configuration.rb:          Hyrax::Engine.routes.url\_helpers.download\_path(file\_set\_id, file: filename)
-   [X] ./lib/hyrax/iiif\_av/spec/shared\_specs/controller\_behavior.rb:  let(:hyrax) { Hyrax::Engine.routes.url\_helpers }
-   [X] ./lib/hyrax/iiif\_av/spec/shared\_specs/controller\_behavior.rb:        # the following code assumes Hyrax::GenericWorksController::IIIF\_DEFAULT\_VERSION is 2;
-   [X] ./app/presenters/concerns/hyrax/iiif\_av/displays\_content.rb:          Hyrax::Engine.routes.url\_helpers.download\_url(solr\_document, file: extension, host: request.base\_url)
-   [X] ./lib/hyrax/iiif\_av/spec/shared\_specs/displays\_content.rb:  let(:parent\_presenter) { double("Hyrax::GenericWorkPresenter", iiif\_version: 2) }
-   [X] ./lib/hyrax/iiif\_av/spec/shared\_specs/displays\_content.rb:            { id: '1', label: 'high', file\_location\_uri: Hyrax::DerivativePath.derivative\_path\_for\_reference(file\_set\_id, 'high.mp3') },
-   [X] ./lib/hyrax/iiif\_av/spec/shared\_specs/displays\_content.rb:            { id: '2', label: 'medium', file\_location\_uri: Hyrax::DerivativePath.derivative\_path\_for\_reference(file\_set\_id, 'medium.mp3') }
-   [X] ./lib/hyrax/iiif\_av/spec/shared\_specs/displays\_content.rb:          let(:parent\_presenter) { double("Hyrax::GenericWorkPresenter", iiif\_version: 3) }
-   [ ] ./app/controllers/concerns/hyrax/iiif\_av/controller\_behavior.rb:        # This forces the manifest action to call Hyrax::ManifestBuilderService.manifest\_for
-   [ ] ./app/controllers/concerns/hyrax/iiif\_av/controller\_behavior.rb:            (Flipflop.cache\_work\_iiif\_manifest? ? Hyrax::CachingIiifManifestBuilder : Hyrax::ManifestBuilderService)

Looking at the above, it appears that this `hyrax-iiif_av` gem considerately plugins into Hyrax.  We’re not seeing lots of overrides but instead see use of extension and configuration; which do need to be revisited but are of a lesser concern.


<a id="orgcc053f4"></a>

## This looks at getting Hyrax to v0.5.0

    cd ~/git/iiif_manifest; git slog v0.3.0..v0.5.0 --no-merges

    * af2e94d — Bump version to 0.5.0 cjcolvar, (2018-10-01)
    * e839c3a — Update readme for presentation 3.0 support Chris Colvard, (2018-10-01)
    * 22dc520 — Fix links pointing to projecthydra-labs cjcolvar, (2018-09-28)
    * 78f34eb — Issue langmap: add nil checking to language_map yingfeng-iu, (2018-07-13)
    * 8191c7f — Issue#116: remove TODO comments yingfeng-iu, (2018-07-10)
    * 103cd3a — Issue#116: rubocop fixes yingfeng-iu, (2018-07-10)
    * eabda39 — Issue#116: rubocop fixes yingfeng-iu, (2018-07-10)
    * b76965e — Issue#116: added language map for all manifest components as needed, updated tests yingfeng-iu, (2018-07-10)
    * 0931320 — Allow for fragments of canvases in ranges and other places through #media_fragment. Allow for interleaving of canvases and ranges within structures or ranges. Chris Colvard, (2018-07-09)
    * 4eb402b — Use bixby to insulate from changes in rubocop Chris Colvard, (2018-06-04)
    * 93fa3c2 — Presentation 3.0 Alpha Support (#19) cjcolvar, (2018-04-26)
    * 2aaaade — bump version to 0.4.0 Julie Allinson, (2018-02-28) (tag: v0.4.0)
    * 16f051d — Add search_service for exposing search endpoint in IIIF presentation manifest Add autocomplete_service for embedding within the search service description Julie Allinson, (2018-01-30)
    * fe84ddb — Allow works to indicate if they are sammelbands Eliot Jordan, (2018-02-20)
    * 8324094 — Use hash-powered IIIF factories. Trey Pendragon, (2018-01-24)
    * 64a20ba — Change where to when in spec contexts to appease rubocop Anna Headley, (2017-11-28)
    * c764146 — Alphabetize gemspec to appease rubocop Anna Headley, (2017-11-28)
    * 8400ee3 — Exclude RecordPropertyBuilder#apply from Metrics/AbcSize Anna Headley, (2017-11-28)
    * 80b3aff — Add viewingDirection as optional data value on manifest, fixes #12 Anna Headley, (2017-11-28)
    * 4c0bf30 — Fix typo in spec context Anna Headley, (2017-11-28)

For items “checked” this means we have either assumed it’s no impact or written about it later on to describe the impact.  There are 8 commits that we would want to revisit to determine the impact of upgrading Hyrax’s iiif\_manifest version to `~> 0.5`.

-   [X] af2e94d — Bump version to 0.5.0 cjcolvar, (2018-10-01)
-   [X] e839c3a — Update readme for presentation 3.0 support Chris Colvard, (2018-10-01)
-   [X] 22dc520 — Fix links pointing to projecthydra-labs cjcolvar, (2018-09-28)
-   [ ] 78f34eb — Issue langmap: add nil checking to language\_map yingfeng-iu, (2018-07-13)
-   [X] 8191c7f — Issue#116: remove TODO comments yingfeng-iu, (2018-07-10)
-   [X] 103cd3a — Issue#116: rubocop fixes yingfeng-iu, (2018-07-10)
-   [X] eabda39 — Issue#116: rubocop fixes yingfeng-iu, (2018-07-10)
-   [ ] b76965e — Issue#116: added language map for all manifest components as needed, updated tests yingfeng-iu, (2018-07-10)
-   [ ] 0931320 — Allow for fragments of canvases in ranges and other places through #media\_fragment. Allow for interleaving of canvases and ranges within structures or ranges. Chris Colvard, (2018-07-09)
-   [X] 4eb402b — Use bixby to insulate from changes in rubocop Chris Colvard, (2018-06-04)
-   [ ] 93fa3c2 — Presentation 3.0 Alpha Support (#19) cjcolvar, (2018-04-26)
-   [X] 2aaaade — bump version to 0.4.0 Julie Allinson, (2018-02-28) (tag: v0.4.0)
-   [ ] 16f051d — Add search\_service for exposing search endpoint in IIIF presentation manifest Add autocomplete\_service for embedding within the search service description Julie Allinson, (2018-01-30)
-   [ ] fe84ddb — Allow works to indicate if they are sammelbands Eliot Jordan, (2018-02-20)
-   [ ] 8324094 — Use hash-powered IIIF factories. Trey Pendragon, (2018-01-24)
-   [X] 64a20ba — Change where to when in spec contexts to appease rubocop Anna Headley, (2017-11-28)
-   [X] c764146 — Alphabetize gemspec to appease rubocop Anna Headley, (2017-11-28)
-   [X] 8400ee3 — Exclude RecordPropertyBuilder#apply from Metrics/AbcSize Anna Headley, (2017-11-28)
-   [ ] 80b3aff — Add viewingDirection as optional data value on manifest, fixes #12 Anna Headley, (2017-11-28)
-   [X] 4c0bf30 — Fix typo in spec context Anna Headley, (2017-11-28)


<a id="org82d1177"></a>

## Let’s look at getting Hyrax to v1.0.0

    cd ~/git/iiif_manifest; git slog v0.5.0..v1.0.0 --no-merges

    * 29dfbd9 — Bump Bundler version Mark Bussey, (2019-08-23) (tag: v1.0.0)
    * 2e8340a — Version bump Mark Bussey, (2019-08-23)
    * 309bc9b — Add initial configuration for CircleCI Mark Bussey, (2019-08-01)
    * 28061f1 — Ensuring that empty DisplayContent values within IIIF V3 manifest generation are handled GriffinJ, (2019-06-10)
    * cee33cc — Bump version to prepare for release cjcolvar, (2019-05-14)
    * d4b9e14 — Don't include # if there isn't any media fragment cjcolvar, (2019-03-12)
    * 1f720f7 — Update README.md Collin Brittle, (2019-02-19)
    * 2033081 — Add support for homepage in V3 Chris Colvard, (2019-02-18)
    * 5dc2941 — Optional authentication service for non-image api-backed resources. Chris Colvard, (2019-02-11)

There are four commits to visit.

-   [X] 29dfbd9 — Bump Bundler version Mark Bussey, (2019-08-23) (tag: v1.0.0)
-   [X] 2e8340a — Version bump Mark Bussey, (2019-08-23)
-   [X] 309bc9b — Add initial configuration for CircleCI Mark Bussey, (2019-08-01)
-   [ ] 28061f1 — Ensuring that empty DisplayContent values within IIIF V3 manifest generation are handled GriffinJ, (2019-06-10)
-   [X] cee33cc — Bump version to prepare for release cjcolvar, (2019-05-14)
-   [ ] d4b9e14 — Don't include # if there isn't any media fragment cjcolvar, (2019-03-12)
-   [X] 1f720f7 — Update README.md Collin Brittle, (2019-02-19)
-   [ ] 2033081 — Add support for homepage in V3 Chris Colvard, (2019-02-18)
-   [ ] 5dc2941 — Optional authentication service for non-image api-backed resources. Chris Colvard, (2019-02-11)


<a id="org6f406df"></a>

## Clarifying the Default Viewer Assumption

In [Hyrax::IiifAv::Configuration#iiif\_av\_url\_builder](https://github.com/samvera-labs/hyrax-iiif_av/blob/888ad531ec08e6c1040d609321972e2147f0c702/lib/hyrax/iiif_av/configuration.rb#L20-) we have a default assumption of `:avalon`

    # A symbol that represents the viewer to render for AV items.
    # Defaults to :avalon. Known to work with :universal_viewer as well
    #
    # @return [:symbol] viewer partial name
    def iiif_av_viewer
      @iiif_av_viewer ||= :avalon
    end
    attr_writer :iiif_av_viewer

Let’s look at how that is used.

    def iiif_viewer
      if representative_presenter.video? || representative_presenter.audio?
        Hyrax::IiifAv.config.iiif_av_viewer
      else
        super
      end
    end

We need to be mindful of [DHyrax::IiifAv::DisplaysIiifAv#iiif\_viewer](https://github.com/samvera-labs/hyrax-iiif_av/blob/888ad531ec08e6c1040d609321972e2147f0c702/app/presenters/concerns/hyrax/iiif_av/displays_iiif_av.rb#L39-L45)
