### ISSUE TITLE
Install IIIF AV gem

### ISSUE THREAD

**Issue by kirkkwang** [notch8/utk-hyku#175]
### Descriptive summary

Currently, UTK does not has a means to handle AV materials.  We should be able to solve this by using the [hyrax-iiif_av](https://github.com/samvera-labs/hyrax-iiif_av) plug-in.

### Rationale

UTK has work types of Audio and Video which will need AV support.  CompoundObject may need this support as well.

### Task List

- [ ] See findings from https://github.com/scientist-softserv/utk-hyku/issues/129
- [ ] Upgrade gem to work with Hyrax 3.x
  - [ ] Bump the hyrax-iiif_av.gemspec (on a branch) to > 0.5 for the iiif_manifest changes.
  - [ ] Bump the hyrax-iiif_av.gemspec (on a branch) to ~> 2.9 and < 5.0 for the hyrax changes.
  - [ ] In the Hyku Gemfile we add a gem reference to hyrax-iiif_av at the new branch.
  - [ ] In the Hyku Gemfile we add a gem reference to iiif_manifest at the 1.x version.
- [ ] Follow the instructions in the gem's [README](https://github.com/samvera-labs/hyrax-iiif_av#readme) and run the generator

### Expected behavior

A Video or Video should render a Universal Viewer.

### Actual behavior

Does not render UV.

### Related work

https://github.com/scientist-softserv/utk-hyku/issues/129

### Testing

- [ ] upload a video (mp4) of your choosing as an `Attachment`
  - [ ] observe that UV renders and the video can be played
- [ ] upload an audio (wav or mp3) of your choosing as an `Attachment`
  - [ ] observe that UV renders and the audio can be played

NOTE: make sure to add `http://pcdm.org/use#IntermediateFile` in the RDF Type field

**Comment by ShanaLMoore** [comment]
# Dev note

reference ATLA's iiif AV gem work

@kirkkwang to schedule a half hr pairing session this week with Rob to review it.

**Comment by ShanaLMoore** [comment]
# QA Results: 
#### This needs some rework. The UV doesn't appear to be rendering.

## VIDEO
- [x]     upload a video (mp4) of your choosing as an Attachment: 
  - [ ]         observe that UV renders and the video can be played

sample file: https://user-images.githubusercontent.com/10081604/204572187-a18f3465-c78d-4547-bd0b-dc021093c31b.mp4

I created an [attachment](https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/54d73506-0fd8-483b-a1d7-1e0bbaf3cda0?locale=en) and uploaded the above file and here are the results: 




![Image](https://user-images.githubusercontent.com/10081604/204572453-4f2bc5c6-fa24-41a4-a35b-5f1ad18e6a61.png)



![Image](https://user-images.githubusercontent.com/10081604/204573480-5ce469b6-04ff-491c-b9f9-e18fdc1f23bb.png)



## AUDIO
- [x]     upload an audio (wav or mp3) of your choosing as an Attachment: 
  - [ ]         observe that UV renders and the audio can be played

sample file: (github doesn't support .mp3 files so I can't attach it)

I created an attachment and uploaded an audio file (mp3). Here are the results: 


![Image](https://user-images.githubusercontent.com/10081604/204573553-a8f59b32-e3b1-4ce9-a55f-bb4709ac768b.png)



![Image](https://user-images.githubusercontent.com/10081604/204573655-2a5d5969-c351-45bc-b66a-292a23d2964e.png)

The play button doesn't play anything.

**Comment by kirkkwang** [comment]
@ShanaLMoore Here are two files I uploaded

Video:
https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/cbe20969-6f0f-4ade-9482-c2a0c7449346?locale=en

Audio:
https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/15ef4848-7eb5-42a5-9930-24ce6242bae6?locale=en

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- video: https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/0ae79560-105a-492e-baf4-7284c98d0b48?locale=en
- audio: https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/8a23dcc1-6975-4956-bffc-94f7482455f9?locale=en


Testing
- [x]  upload a video (mp4) of your choosing as an Attachment
     - [x]  observe that UV renders and the video can be played
- [x]  upload an audio (wav or mp3) of your choosing as an Attachment
     - [x]  observe that UV renders and the audio can be played

NOTE: make sure to add http://pcdm.org/use#IntermediateFile in the RDF Type field

<details><summary>Videos and audio can be played from the UV</summary>



![Image](https://user-images.githubusercontent.com/29311858/206598155-75d24b73-5d1f-43c2-aec9-8f7a88fc9803.jpg)


![Image](https://user-images.githubusercontent.com/29311858/206598160-d174e158-ff29-4a62-9a3f-dfb1cdf48403.jpg)

</details>

**Comment by markpbaggett** [comment]
I've tested audio and video on staging and both look good! 😎

**Comment by markpbaggett** [comment]
@kirkkwang per our meeting on december 20, 2022, i'm moving this one to `Done`.  we will review again once we get to importing a/v.
