### ISSUE TITLE
📎 SOW: CAS SSO setup

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#2]
# Summary
ref:
- #410 
- #2

This instance will be customized to incorporate Shibboleth or CAS for single sign on authentication per UTK requirements. Notch8 has previous experience in both, and recommends CAS if UTK has no requirement for Shibboleth.

consider installing omniauth-cas gem

DO NOT disable regular username/password logins

# Acceptance Criteria
- [ ] As a user, I can log in through CAS SSO

# Screenshots/Videos

# Testing Instructions

# TODO: 
- [x] https://github.com/scientist-softserv/utk-hyku/issues/410#issuecomment-1581319245
- [ ] Does this ticket need to be completed first? https://github.com/scientist-softserv/utk-hyku/issues/368
- [ ] get sso/utk accounts for team v
- [x] #25
- [ ] #368 
- [x] #207

# Notes
- do we need to remove options to log in without SSO for production?

- First step requires changing the production domain (need to schedule pairing time with Rob)
- Need UTK account to test this

**Comment by ShanaLMoore** [comment]
name of the CAS gem? 
projects that have it done? wustl, dot, rutgers, linn benton (Rob has the most experience for this)
can we make sprint out of specific work, across many projects? (ie: sso => have rob walk us through one project to train up another team mate, and divide/conquer)

ESSI uses [omniauth-cas](https://github.com/IU-Libraries-Joint-Development/essi/commit/c9ea9a68b1013f22b442d2c814802e0662772052)

**Comment by jillpe** [comment]
**2 gem options:**

- [Omniauth](https://github.com/dlindahl/omniauth-cas): This is the preferred one (it is also compatible with other forms of SSO)
- [Devise Auth](https://github.com/nbudin/devise_cas_authenticatable)

**Potentially Helpful PRs**
https://gitlab.com/notch8/dot/-/issues/5
https://gitlab.com/notch8/dot/-/issues/4
https://gitlab.com/notch8/wustl-hyrax/-/issues/12
https://playbook-staging.notch8.com/en/samvera/SSO/saml

**Comment by jillpe** [comment]
**Point of Contact:** William Richardson (wkrich@utk.edu)
**Domain:** digitalcollections.lib.utk.edu.

https://assaydepot.slack.com/archives/C0396LSM06P/p1674051279877639?thread_ts=1673982511.234789&cid=C0396LSM06P

**Comment by markpbaggett** [comment]
This looks good to me in terms of scope of work.  We just need users to be able to authenticate via CAS.  I assume this means all administrators will login via CAS rather than using a shared account.

**Comment by jillpe** [comment]
@markpbaggett There is currently a shared account, but SSO is usually for everyone to have their own account and then a super-admin can change their role

**Comment by crisr15** [comment]
Once users log in the first time there permissions are handled inside of hyku.  As Jill mentioned, a super-admin or another admin can upgrade permissions for users and they will retain those permissions.

**Comment by ShanaLMoore** [comment]
@markpbaggett Once we start this work, I would think that we would need UTK accounts so that we can test the SSO works. What information do you need from us to set this up?

**Comment by jillpe** [comment]
Mark is point of contact to pair with on this ticket

**Comment by ShanaLMoore** [comment]
Per Jill, "SSO is being put into 3 projects rn so Rob, Braydon and Lea Ann are putting the code into Hyku (it just needs to be tested before it's available) - so we should be able to just pull the code. They are meeting sometime this week/next to do the testing/give us the code and Kirk will be joining that meeting. And then from there we need to meet with Mark to make sure all of the domains/ssl certs are in their system correctly (April will be a part of that) and to map the metadata fields"

**Comment by jillpe** [comment]
Waiting for UTK IT to enable CAS support properly and merging with upstream Hyku changes.

**Comment by markpbaggett** [comment]
I think this is done, but how can we bypass CAS or get certain users the admin privileges associated with the default admin set?

**Comment by markpbaggett** [comment]
@jillpe I'm going to do my best to explain this one, but let me know if we need my to do some show and tell.

Right now, it seems like CAS is working for “authorization” but not “authentication.” If you sign into CAS via the digital collections tenant, authorization works. If you sign it with your utk account again, it works as well but the account it registers is [username@example.com](mailto:username@example.com).  you can create a [username@utk.edu](mailto:username@utk.edu) account from the users screen, but it still wants to log you into that [account@example.com](mailto:account@example.com).
 
Mikerealized that if you go to hykuadmin, you can register an @utk.edu account and login to it via the tenant, but when you do this it’s bypassing cas and instead using the auth information you set from [hykuadmin.lib.utk.edu](http://hykuadmin.lib.utk.edu/).

I think our questions are:

1. should authentication and authorization both be working via cas?
2. if so, how should we be registering a new user?
3. this might all be fixed if for some reason it didn’t try to create [username@example.com](mailto:username@example.com) when you authenticate as [username@utk.edu](mailto:username@utk.edu) from the digitalcollections tenant.

**Comment by orangewolf** [comment]
@markpbaggett I'm sorry I wasn't able to get to this sooner. This is a settings issue. It needed to be set in admin when the sso was set up. 
<img width="1728" alt="Screenshot 2023-09-13 at 21 43 26" src="https://github.com/scientist-softserv/utk-hyku/assets/1054448/f0c4ba73-f3a6-4fac-b4ed-20558be5192c">

I've set it and changed the example.com users to be utk.edu emails instead. on next log in they should sync up just fine

**Comment by jillpe** [comment]
Confirmed in client meeting 2023-09-14, this ticket can be closed
