### ISSUE TITLE
Copy over flex overrides from IU

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#240]
### Descriptive summary

This ticket was created after reviewing #157 

We would like to include all of the following customization that Indiana University did. However, instead of doing them as UTK overrides, we would like them to be included in [Allinson Flex (flex) proper.](https://github.com/samvera-labs/allinson_flex)

- [ ]  [ESSI-1465][ESSI-1466] log profile construction errors 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/ac3585b326f8266d4ab3c18b1aa7a19d2275dfc6
- [ ]  [ESSI-1382] Refactor property texts into separate method 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/93eaa1ab3787118fc63636c1a1650206b81e7ac2
- [ ]  [ESSI-1321][ESSI-1445] add admin_only indexing display modifier 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/4401fa19040539cf75b2c24cddae3b9b71879370
- [ ]  [ESSI-1465][ESSI-1466] raise more specific ProfileText error messages 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/3f19bdeb5394e378f07fe0f1500bc8b9501e52ce
- [ ]  [ESSI-1539] Tweak dynamic indexing results: make ActiveTriples Arrays 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/dbcbb22d82744e62bc3a580f7b27ca640236896f
- [ ]  [ESSI-1370] Soften condition for AllinsonFlex::Profile before_destroy… 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/0929763f445879277a66278cf16958226a1a14e8
- [ ]  [ESSI-1519] Skip allinson_flex load in Collections authority 
MR: https://github.com/IU-Libraries-Joint-Development/essi/commit/581fcd1a983dd3dc310b2721d4e9334f9fd76f95
- [ ]  [ESSI-1692] dynamic manifest metadata #480 https://github.com/IU-Libraries-Joint-Development/essi/pull/480
- [ ]  [ESSI-1614] catch errors rendering #new with a new AllinsonFlex profile #455 https://github.com/IU-Libraries-Joint-Development/essi/pull/455
- [ ]  [ESSI-1539] tweak dynamic indexing #369 https://github.com/IU-Libraries-Joint-Development/essi/pull/369
- [ ]  [ESSI-1370] Bulkrax export bugs #336 https://github.com/IU-Libraries-Joint-Development/essi/pull/336/files
- [ ]  [ESSI-1135] [ESSI-1214] Fix dynamic facets #258 https://github.com/IU-Libraries-Joint-Development/essi/pull/258/files

### Rationale

Includes improvements and optimizations to the gem, that everyone can benefit from.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

**Comment by jillpe** [comment]
@jillpe create an allinsonflex ticket with this information

**Comment by jillpe** [comment]
No longer necessary
