### ISSUE TITLE
Spike: intermediateFile reorientation

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#404]
# Summary
ref: #72 
We need to reorient ourselves with where we are at in the process, so we can break down the remaining tasks. If there are questions we need answers to to unblock the task breakdown, we need to take note of them in a follow up spike ticket and tag it in the [meeting notes](https://docs.google.com/document/d/1GsoeK7gkBq3yziAVIK4Fijihd7jNo5nkc0Fnj8K1-B4/edit#)

# Acceptance Criteria
- [x] Intermediate files are displayed in the UV 
- [x] No preservation files are displayed in the UV

# Todo
- [ ] https://github.com/scientist-softserv/utk-hyku/issues/72
- [ ] https://github.com/scientist-softserv/utk-hyku/pull/399
- [ ] https://github.com/scientist-softserv/utk-hyku/issues/97

# Related PRs
- [ ] #370 
- [ ] #399

@kirkkwang when you have a chance can you please provide any info on the status of your [draft PR](https://github.com/scientist-softserv/utk-hyku/pull/399/files)?

**Comment by kirkkwang** [comment]
@DeonFranklin i have a branch called `show-uv-only-for-intermediate-files` that may help

I think it's pretty much good to go, maybe give it a spin

**Comment by DeonFranklin** [comment]
@kirkkwang will do! thank you!!

**Comment by kirkkwang** [comment]
> @kirkkwang will do! thank you!!

No prob!

Oh you would need to reindex though

**Comment by jillpe** [comment]
closed - tickets all tickets are deployed to staging
