### ISSUE TITLE
Spike: Accessibility Reorientation

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#407]
# Summary
ref: #393  
We need to reorient ourselves with where we are at in the process, so we can break down the remaining tasks. If there are questions we need answers to to unblock the task breakdown, we need to take note of them in a follow up spike ticket and tag it in the [meeting notes](https://docs.google.com/document/d/1GsoeK7gkBq3yziAVIK4Fijihd7jNo5nkc0Fnj8K1-B4/edit#)

# Acceptance Criteria

- [ ] Application meets WCAG 2.0 aa Compliance
- [ ] Videos have ability to enable closed captions
- [ ] Admin Dashboard passes Accessibility Audit

# TODO:
- [x] https://github.com/scientist-softserv/utk-hyku/issues/41
- [x] https://github.com/scientist-softserv/utk-hyku/issues/43
- [x] https://github.com/scientist-softserv/utk-hyku/issues/386
- [x] https://github.com/scientist-softserv/utk-hyku/issues/387
- [ ] https://github.com/scientist-softserv/utk-hyku/issues/393
- [x] https://github.com/scientist-softserv/utk-hyku/issues/403

# Note
- [ ] https://www.w3.org/WAI/WCAG2AA-Conformance
- [ ] https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#principle1
- [ ] Link to [last audit](https://github.com/scientist-softserv/utk-hyku/files/11287664/Report.for.https___test.hykucommons.org_.pdf)
