### ISSUE TITLE
🦄 Spike: Basic Search Functioning Reorientation

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#408]
# Summary
ref: #392 
We need to reorient ourselves with where we are at in the process, so we can break down the remaining tasks. If there are questions we need answers to to unblock the task breakdown, we need to take note of them in a follow up spike ticket and tag it in the [meeting notes](https://docs.google.com/document/d/1GsoeK7gkBq3yziAVIK4Fijihd7jNo5nkc0Fnj8K1-B4/edit#)

# Acceptance Criteria

- [x] Current status of the basic search functioning tasks are documented (https://github.com/scientist-softserv/utk-hyku/issues/423)
- [x] Relevant prs, tickets, notes, etc. are documented 
- [x] Determining how much is left and if additional breakdown is needed

# Todo

Remaining work:

- [x] https://github.com/scientist-softserv/utk-hyku/issues/420
- [x] #425
- [x] #426
- [x] #424
- [x] #421
- [x] #422
- [x] #423
- [x] https://github.com/scientist-softserv/utk-hyku/issues/427

**Comment by jillpe** [comment]
Notes from Crystal on ranking:
Ranking
* It is an algorithm
  * The fields (i.e. title, description, etc.) that show the search term all have different points associated with it (i.e. title = 1, description = 3)
    * Item with the most points sorts to the top of the results
* We need client to tell us which document should show higher and then we go and search tune using this algorithm
  * Ask to prioritize the terms
  * If they change their metadata fields, tuning will need to happen again
* Lea Ann is knowledgeable on this

**Comment by laritakr** [comment]
Remaining work:
- #420 
-
