### ISSUE TITLE
🎁Add facets for "facetable" properties

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#425]
related to
- #408 
- #392

# Todo
- https://github.com/scientist-softserv/utk-hyku/pull/463

Ideally this work will be implemented via allinson flex. As a last resort, manually set them.
Add all missing facets based on metadata profile.
- [ ] Identify remaining terms to be added
- [ ] Manually add remaining terms
- [ ] Make a ticket to get it working with AllinsonFlex

Related to #426

- Potentially related to potentially related to https://github.com/samvera-labs/allinson_flex/issues/53

# Testing Instructions
- [ ] Create a new work or edit an existing work
- [ ] Add faceted properties to the work, which include:
  - [ ] form_local
  - [ ] intermediate_provider
  - [ ] keyword
  - [ ] language
  - [ ] language_local
  - [ ] license
  - [ ] resource_type
  - [ ] rights_statement
  - [ ] spatial
  - [ ] subject
  - [ ] temporal
- [ ] when doing a catalog search for that work's title, observe that those fields show up on the left side as facets

# Notes

It looks like Allinson flex has a switch statement to determine the solr suffix -  
https://github.com/samvera-labs/allinson_flex/blob/ab9b353a3034c182218356c9320ebe0b6b952a79/app/services/allinson_flex/dynamic_schema_service.rb#L207-L227

AF may store what is facetable but it doesn't auto connect anything to the catalog controller for it to facet automatically. 

Maybe check if ESSI already have an implementation for this?

**Comment by jillpe** [comment]
remaining terms are listed as facetable in the profile

**Comment by ShanaLMoore** [comment]
If AllinsonFlex isn't capable of doing this, manually add them for now and create a separate ticket for AllinsonFlex to do it automatically.

**Comment by laritakr** [comment]
`facetable fields` based on most recent metadata profile:
- form_local
- intermediate_provider
- keyword
- language
- language_local
- license
- resource_type
- rights_statement
- spatial
- subject
- temporal

Current facet fields in catalog_controller:
![Screenshot 2023-07-07 at 3 58 24 PM](https://github.com/scientist-softserv/utk-hyku/assets/17851674/776e8776-f285-44f6-aab4-2aeda7f1a2ed)

**Comment by ShanaLMoore** [comment]
Per LaRita, indexing seems to be working correctly but the dynamic catalog behavior is not being included anywhere.
ESSI is including it in their catalog controller: 
https://github.com/search?q=repo%3AIU-LibrariesJointDevelopment%2Fessi%20DynamicCatalogBehavior&type=code

**Comment by ShanaLMoore** [comment]
@laritakr We were able to figure out #[425](https://github.com/scientist-softserv/utk-hyku/issues/425) :tada: Turns out there's support for facets with allinson flex after all. With your tip, we figured out it wasn't being included. With Deon, we figured out it wasn't working because of a minor but significant typo.
After correcting that, the facets appears as defined by the m3 metadata profile.

NEXT STEPS:
@DeonFranklin  will submit the typo fix to allinson flex.
Once that gets merged, he will submit a PR that
1. has the module included in the catalog controller
2. updates allinson flex to pull in the fix

Thanks for driving @DeonFranklin

**Comment by DeonFranklin** [comment]
- https://github.com/scientist-softserv/utk-hyku/pull/464

**Comment by DiemBTran** [comment]
~**Needs further review:**~ **EDIT: This passes SoftServ QA** The language issues arise from the M3 profile, **not** the work that was done here. So this ticket passes.

tested on:
- work show page: https://qa.utk-hyku-staging.notch8.cloud/concern/books/6dc76370-9865-46ef-b49c-fcdd4c56e429?locale=en
- search catalog: https://qa.utk-hyku-staging.notch8.cloud/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=2023-07-18+%F0%9F%8E%81Add+facets+for+%22facetable%22+properties+%23425

# Testing Instructions
- [x] form_local
- [x] intermediate_provider
- [x]  keyword
- [x]  language
- [ ]  language_local
  - Something is fishy about `Language` and `Local Language`. I typed in `Vietnamese` for `Language` and `English` for `Language local`. When I save the form,  `Language: English` appears twice on the work show page and search catalog. `Language: Vietnamese` doesn't appear at all. Editing the work shows that `Vietnamese` is overridden with `English`.
  - screen recording: https://share.getcloudapp.com/rRuzObRD
- [x]  license
- [x]  resource_type
- [x]  rights_statement
- [x]  spatial
- [x]  subject
- [x]  temporal

<details><summary>Facetable properties appear in search facets</summary>

![Book 2023-07-18 🎁Add facets for facetable properties #425 ID 6dc76370-9865-46ef-b49c-fcdd4c56e429 Hyku 2023-07-18 at 2 40 11 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/67542ddb-e7a0-4456-825a-3bbb784ceb77)
![Index Catalog Hyku 2023-07-18 at 2 40 25 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/970f41be-7c4d-4412-abce-7731ff7b82ba)

</summary>

**Comment by josh-morgan117** [comment]
@laritakr for clarification, based on what I've read for the ticket, it seems like y'all have determined how to get AllinsonFlex to do this automatically based on the m3 profile instead of having to manually add them, correct?

**Comment by laritakr** [comment]
@kidon0011 Yes, we found indications that it should have been working, and found several small bugs that were causing the problem. So it works now. :)

**Comment by jillpe** [comment]
Verification on production blocked until #358 resolved
