### ISSUE TITLE
Milestone 3/4 testing

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#529]
# Summary
We want to verify where we are at on the following Milestone SOW's. We think they are mostly covered, but need to verify.

- Bulkrax export
- Groups and Roles
- Newspapers

# Accepted Criteria
- [x] Bulkrax export status is documented
- [x] Groups and Roles status is documented
- [x] Newspapers status is documented

**Comment by jillpe** [comment]
**Exporter notes**
Creating an Export
* `Create and Export` Button: ✅ 
* `Create` Button: ❓ 
  * It does create the exporter. Once the exporter is created though, there is no way to run it
  
Export Type Options:
* Collection
    * [Metadata only: ✅](https://dc.utk-hyku-staging.notch8.cloud/exporters/5?locale=en)
    * [Metadata and Files: ✅](https://dc.utk-hyku-staging.notch8.cloud/exporters/6?locale=en)
* Importer
    * [Metadata only :✅](https://dc.utk-hyku-staging.notch8.cloud/exporters/7?locale=en)
    * [Metadata and File ❓ ](https://dc.utk-hyku-staging.notch8.cloud/exporters/9?locale=en)
      * the zip is not able to be opened
* Work
    * [Metadata only: ✅](https://dc.utk-hyku-staging.notch8.cloud/exporters/10?locale=en) 
    * [Metadata and File: ✅ ](https://dc.utk-hyku-staging.notch8.cloud/exporters/11?locale=en)
* All
    * [Metadata only: ✅ ](https://dc.utk-hyku-staging.notch8.cloud/exporters/12?locale=en)
    * [Metadata and File: ✅ ](https://dc.utk-hyku-staging.notch8.cloud/exporters/13?locale=en)

Editing an exporter ❌ 
* `Update Importer` and `Update and Re-export all items` buttons do NOT work

Deleting an exporter  ✅

**Comment by jillpe** [comment]
**Newspaper**

Comments from Mark:

> think we should just keep things simple with the newspaper title being a colleciton, the volume being a collection, and each issue just being something close to a book except with alto xml instead of hocr and ocr for each page.  i think if we do that, things should be much easier for you all as it’s essentially the same as book just with the ocr done a slightly different way.

> 
To Do:
- Need to verify this work type will work through derivative rodeo

[Sample Files for Testing](https://drive.google.com/file/d/191P6hRpUxrWsBqVV5dALR3YW4YS7LZhJ/view?usp=sharing)

**Comment by jillpe** [comment]
**Groups and Roles**

[Workflow Mark requested:](https://github.com/scientist-softserv/utk-hyku/issues/4#issuecomment-1531653670)
- We could have one admin set that all participants can deposit into that goes through review - and then the default admin set would remove permissions for everyone except admins to deposit into. This would then give you the ability to have an administrators or chosen set of ppl submitting without review and everything else goes through a review process
  - UTK said this would be okay for right now, but still wanted to have the groups and roles features for their future workflows

Testing based on [Groups and Roles documentation](https://github.com/samvera/hyku/wiki/Groups-with-Roles-Feature#defining-roles-users-and-groups)
* Groups
  * [Do not have the ability](https://dc.utk-hyku-staging.notch8.cloud/admin/groups/new?locale=en)
  
* Workflow Roles
  * Have the option to assign roles, however, it does not appear to save
    * Ex. admin@example.com should only have ability to deposit/access Default Admin set, however has the ability to create a work type for all of the sets (Mountains, Default Admin, Submission Review

* Users
  * [Could not add users/roles through Dashboard](https://dc.utk-hyku-staging.notch8.cloud/admin/users?locale=en)
    * Shows that the user's status is pending (ex. jill@scientist.com user), however email was never sent to her

**Comment by orangewolf** [comment]
> Create Button: ❓
> It does create the exporter. Once the exporter is created though, there is no way to run it

You edit the exporter and when you save it lets you run it - that is how import works as well. 

> [Metadata and File ❓](https://dc.utk-hyku-staging.notch8.cloud/exporters/9?locale=en)
the zip is not able to be opened

Seems like a bug, hopefully a small one

> Editing an exporter ❌

Bug, and that explains your issue with the first item =-)
