### ISSUE TITLE
EPIC: All children files show on parent works

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#83]
# Summary

- [ ] On parent works, all children files should show in the viewer (where applicable).

- [ ] The children should also be able to be displayed on their own.

- [ ] The user should also be able to search for child OCR in the parent UV

- [ ] Consider an implementation that can be easily shared amongst the community (such as a gem). 

This is done in lv

# Acceptance Criteria

- [ ] All children files show on parent works (where applicable)

# Screenshots or Video

# Testing Instructions

# Notes

TODO: 

[look at IU's SOW  && look for and link LV PRs](https://github.com/scientist-softserv/utk-hyku/issues/155#issuecomment-1298956429) - #155 

Other potential spike tickets: 

Discovery - what is everyone asking for? - #156 
Planning - how should we break this down? - #157

**Comment by ShanaLMoore** [comment]
Spike 1 - look at IU's SOW && look for and link LV PRs #155 
Spike 2 - What are the community's needs? #156 
Spike 3 - How can we make this into a gem? #157

**Comment by ShanaLMoore** [comment]
Search Parent/Child Results EPIC: https://gitlab.com/notch8/louisville-hyku/-/issues/100
    Render child works in the UV: https://gitlab.com/notch8/louisville-hyku/-/issues/53
    Search for child OCR from parent UV should return results: https://gitlab.com/notch8/louisville-hyku/-/issues/149
    Child metadata search within the UV should highlight child matches: https://gitlab.com/notch8/louisville-hyku/-/issues/143
    Set parent thumbnail: https://gitlab.com/notch8/louisville-hyku/-/merge_requests/59
    catalog searching for child (like ATTACHMENT) metadata should return parents: https://gitlab.com/notch8/louisville-hyku/-/issues/134
    uv is displayed when jpg derivatives are available: https://gitlab.com/notch8/louisville-hyku/-/issues/55
    Newspaper Work: https://gitlab.com/notch8/louisville-hyku/-/issues/26
    make all metadata fields searchable: https://gitlab.com/notch8/louisville-hyku/-/merge_requests/167

**Comment by jillpe** [comment]
closed - duplicate of #358
